### ISSUE TITLE
Rescript Emeral to work when you have 5 shields

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#15]
Hey, is it possible for Emeral to first select a card from hand, select a random one from shields, pick up the shield and put down the card from hand, so that you could use it's effect even with 5 shields available?

![image](https://user-images.githubusercontent.com/37833135/55821979-f7607e80-5afe-11e9-81d2-5e2affd9d413.png)

**Comment by Hello23-Ygopro** [comment]
Thanks, I didn't think of it! Here's the update: https://github.com/Hello23-Ygopro/ygopro-dm/commit/5068f39c932ed62203d4f6053a0bbb83f1365bfd

**Comment by szefo09** [comment]
Thanks! But it seems like after the change the shield is returned  to hand but the card from hand is sent to GY, and not put as a shield.

**Comment by Hello23-Ygopro** [comment]
Here's what should happen when you summon _Emeral_:
1. If there's a card in your hand, you will get the option to trigger its effect.
2. If you select yes, you must select a card from your hand to add as a new shield.
3. If all your spell & trap zones are occupied the selected card is put into the graveyard (unofficially), otherwise it becomes a new shield.
4. You choose one of your shields at random (unofficially) to return to your hand.

Does it follow in this order?

**Comment by szefo09** [comment]
![2019-04-09_22-47-29](https://user-images.githubusercontent.com/37833135/55834159-87132680-5b19-11e9-94b5-aae9494645f9.gif)

Seems so!

**Comment by szefo09** [comment]
Can’t your 3. and 4. be switched in place so that you can replace the shield by picking the old one up and then placing one from hand instead of putting a card from hand to the GY?

**Comment by Hello23-Ygopro** [comment]
Could you list the steps on how you want it to resolve?

**Comment by szefo09** [comment]
1) If there's a card in your hand, you will get the option to trigger its effect.
2) If you select yes, you must select a card from your hand to add as a new shield.
3) You choose one of your shields at random (unofficially) to return to your hand and return it to hand.
4) The selected card in hand becomes a new shield (Becase there's an empty spot for it now).
