### ISSUE TITLE
Issue with not activated shield trigger cards

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#21]
Hey, a situation occured during a duel where I had Tornado Flame as a shield, It got destroyed but becase opponent had no targets I kept it in hand. Afterwards I noticed that I was able to cast that spell even without having 5+ mana in my mana zone. It happened for my opponent as well with other shield trigger that he didn't want to activate when the shield was destroyed.

**Comment by Hello23-Ygopro** [comment]
I may have found the issue. The `Card.IsCanCastFree` function, which is included for each spell, checks if a spell can be cast for no cost:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/d2d1328802fde960df98d6aa4fbcc20bb5371ebf/expansions/utility_dmtcg.lua#L140

Broken shields are included in this function because they have the flag effect `DM_EFFECT_BROKEN_SHIELD`. The reason why you can cast certain spells for free during your turn is because that flag effect didn't reset in a way that prevents you from casting it for free: https://github.com/Hello23-Ygopro/ygopro-dm/blob/d2d1328802fde960df98d6aa4fbcc20bb5371ebf/expansions/script/c24000000.lua#L450

I'm still deciding on the best way to reset it. I may have to update some of the shield-related functions too. I'm also working on a more optimal way to implement the "Shield trigger" ability, without needing the `dm.AddShieldTriggerCastEffect` function.

**Comment by szefo09** [comment]
Thank you for your efforts!

**Comment by Hello23-Ygopro** [comment]
I've decided to move the flag effects to the `Duel.BreakShield` function with [this patch](https://github.com/Hello23-Ygopro/ygopro-dm/commit/2b58286ed0cb66f999a868fe4f0216cc50a08906). The "Broken shield" message may appear on the wrong cards for some YGOPros, but I think it may have solved your issue.

**Comment by Hello23-Ygopro** [comment]
[This commit](https://github.com/Hello23-Ygopro/ygopro-dm/commit/cf993e2d04e21848e2bd2cde154228d5a86cfd40) removed the `dm.AddShieldTriggerCastEffect` function. Now it's not necessary to include it for spells that have "Shield Trigger". I haven't fully tested it yet and there are some issues with _Pokolul_. I don't know if it's related.

**Comment by szefo09** [comment]
Ok, I’ll go ahead and implement the commits to my server :)
