### ISSUE TITLE
Issue with dm.SelfDestroyOperation()

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#4]
Examples:
Attack the player with Marrow Ooze, the Twister (24002032)
Expected result: Marrow Ooze gets destroyed after the shield is destroyed.
Current result: Marrow Ooze stays on the field

Block an attack of a weaker creature using Bloody Squito 24001046
Expected result: Creature dies, Bloody Squito gets destroyed becase it wins a battle.
Current result: Creature dies, Bloody Squito stays on the field.

**Comment by Hello23-Ygopro** [comment]
> Current result: Creature dies, Bloody Squito stays on the field

This might've fixed it: https://github.com/Hello23-Ygopro/ygopro-dm/commit/070d1080957bc96e8bc16caf4272398a649af1c2

> Block an attack of a weaker creature using Bloody Squito 24001046
> Expected result: Creature dies, Bloody Squito gets destroyed becase it wins a battle.
> Current result: Creature dies, Bloody Squito stays on the field.

Unsolved: I remember encountering a similar issue in YGOPro-KJ. It's probably this line that's causing it:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/53a152a3e8bc40e3105b65bf999593cd1782aa87/expansions/script/c24000000.lua#L464
`REASON_RULE` has to be included because the losing creature is treated as being destroyed by a game mechanic and it won't work if `REASON_BATTLE` is included.

**Comment by Hello23-Ygopro** [comment]
> Block an attack of a weaker creature using Bloody Squito 24001046
> Expected result: Creature dies, Bloody Squito gets destroyed becase it wins a battle.
> Current result: Creature dies, Bloody Squito stays on the field.

This might've fixed it: https://github.com/Hello23-Ygopro/ygopro-dm/commit/af0c7a540388b541b330efcf7ba36f8cba6b804d
